import { 
    ChartLine, 
    Map, 
    GraduationCap, 
    Flower2, 
    ClipboardCheck, 
    Image, 
    MessageSquare, 
    Users, 
    Music, 
    Settings, 
    Hospital, 
    Contact, 
    Cpu, 
    FileText, 
    Activity, 
    TriangleAlert, 
    Info, 
    Zap, 
    Scissors, 
    Anchor, 
    Play, 
    Pause, 
    Square, 
    Download, 
    Printer, 
    Send, 
    Plus, 
    Trash2, 
    Search, 
    LogOut, 
    CheckCircle2, 
    Lock, 
    Clock, 
    Bell, 
    Shield,
    UserPlus,
    ArrowRight,
    ArrowLeft,
    Check,
    CircleCheck,
    AlertTriangle,
    Phone,
    MessageCircle,
    Wind,
    Settings2,
    Ban,
    Filter,
    UserPen,
    Trash,
    ShieldAlert,
    Key,
    Megaphone,
    UserCheck,
    Stethoscope,
    Briefcase,
    Lightbulb,
    BookOpen,
    Accessibility,
    ShieldCheck,
    Bot,
    Apple,
    Smartphone,
    Laptop,
    Save,
    ChevronDown,
    ChevronUp,
    Expand,
    Compass,
    Calendar,
    Star,
    Trophy,
    Hourglass,
    Volume2,
    VolumeX,
    X,
    Sun,
    Moon,
    Ghost,
    Power,
    Leaf,
    Flag,
    Target,
    Palette,
    GripVertical,
    CloudRain,
    Cake,
    Shirt,
    Terminal,
    ChevronLeft,
    ChevronRight,
    Award,
    ListChecks,
    FlagTriangleRight,
    Home,
    Ear,
    Eye,
    Hand,
    ArrowUpRight
  } from 'lucide-react';
  
  export const Icons = {
    ChartLine,
    Map,
    GraduationCap,
    Spa: Flower2,
    ClipboardCheck,
    Image,
    MessageSquare,
    Users,
    Music,
    Settings,
    Hospital,
    Contact,
    Cpu,
    FileMedical: FileText,
    HeartPulse: Activity,
    TriangleExclamation: TriangleAlert,
    CircleInfo: Info,
    BoltLightning: Zap,
    Scissors,
    Anchor,
    Play,
    Pause,
    Stop: Square,
    Download,
    Print: Printer,
    PaperPlane: Send,
    Plus,
    TrashCan: Trash2,
    Search,
    LogOut,
    CircleCheck,
    Lock,
    Clock,
    Bell,
    Shield,
    UserPlus,
    ArrowRight,
    ArrowLeft,
    Check,
    CheckCircle2,
    AlertTriangle,
    Phone,
    MessageCircle,
    Wind,
    Gears: Settings2,
    Ban,
    Filter,
    UserPen,
    Trash,
    ShieldVirus: ShieldAlert,
    Key,
    // Screwdriver, (Removed because it is not imported or initialized)
    Bullhorn: Megaphone,
    UserCheck,
    UserDoctor: Stethoscope,
    Briefcase,
    Lightbulb,
    BookOpen,
    Accessibility,
    //    UserShield, (Removed because it is not imported or initialized)
    ShieldCheck,
    Bot,
    Apple,
    Smartphone,
    Laptop,
    Save,
    ChevronDown,
    ChevronUp,
    Expand,
    Compass,
    Calendar,
    Star,
    Trophy,
    Hourglass,
    VolumeHigh: Volume2,
    VolumeX,
    X,
    Sun,
    Moon,
    Ghost,
    Power,
    Leaf,
    Flag,
    Target,
    Palette,
    GripVertical,
    CloudRain,
    Cake,
    Shirt,
    Terminal,
    ChevronLeft,
    ChevronRight,
    Award,
    ListChecks,
    FlagTriangleRight,
    Home,
    Ear,
    Eye,
    Hand,
    ArrowUpRight,
    FileText
  };